---
title: "長庚大學 大數據分析方法 作業三"
output: github_document
---

install.packages("rvest")
## 網站資料爬取
```{r}

library(rvest) 
PTT <- "https://www.ptt.cc/bbs/LoL/index.html"
PTT02 <- "https://www.ptt.cc/bbs/LoL/index7122.html"
PTT03 <- "https://www.ptt.cc/bbs/LoL/index7121.html"
PTT04 <- "https://www.ptt.cc/bbs/LoL/index7120.html"
PTT05 <- "https://www.ptt.cc/bbs/LoL/index7119.html"
PTT06 <- "https://www.ptt.cc/bbs/LoL/index7118.html"
PTT07 <- "https://www.ptt.cc/bbs/LoL/index7117.html"
PTT08 <- "https://www.ptt.cc/bbs/LoL/index7116.html"
b <- c(PTT,PTT02,PTT03,PTT04,PTT05,PTT06,PTT07,PTT08)

frameAll <- NULL
for(n in b){
    PTTContent <- read_html(n)
    post_title <- PTTContent %>%
        html_nodes(".title") %>%
        html_text()
    post_title
    
    post_nrec <- PTTContent %>%
        html_nodes(".nrec") %>%
        html_text()
    post_nrec
    
    post_author<- PTTContent %>% 
        html_nodes(".author") %>% 
        html_text()
    post_author
    
    post_date<- PTTContent %>% 
            html_nodes(".date") %>% 
            html_text()
    post_date
    
    pppt <- data.frame( title = c(post_title),
                        pushNum = c(post_nrec),
                        author = c(post_author),
                        date = c(post_date) )
    pppt
    
    frameAll <- rbind( frameAll,pppt )
    Sys.sleep(sample(3:5, 1))
}


```

## 爬蟲結果呈現
```{r}
knitr::kable(
    frameAll[1:151,c("title","pushNum","author","date")])

```

## 解釋爬蟲結果 
```{r}
dim(frameAll)
```

LOL眾多文章裡[公告] LoL 英雄聯盟板板規告和[電競] 近期賽事的文章，
就算日期是以前的文章，但仍然排在版面上。
還有當title欄位是本文已被刪除，那author欄位就會是空白的
author欄位rainnawind作者，每次發文回應人數都很熱門!


```{r}
table(frameAll$title)
```

遇到節日，例如：兒童節、清明節，鄉民就會發關於lol廢文
最近eltar 發關於賽後訪問的文章，也非常熱門!!

